Class {
	#name : #Tierra,
	#superclass : #Topografia,
	#category : #'OO2-TP4-Topografia-Model'
}

{ #category : #'as yet unclassified' }
Tierra >> = unaTopografia [ 

^ unaTopografia igualATierra 
]

{ #category : #calculating }
Tierra >> calcularProporcionAgua [
^0
]

{ #category : #'as yet unclassified' }
Tierra >> igualAAgua [ 
^false
]

{ #category : #'as yet unclassified' }
Tierra >> igualATierra [
^true
]
